### ISSUE TITLE
Error calling "DownloadAndParseAsync" function

### ISSUE THREAD

**Issue by GhostScissors** [NotOfficer/EpicManifestParser#4]
I tried implementing this in a project I am working on but when calling [DownloadAndParseAsync](https://github.com/NotOfficer/EpicManifestParser/blob/master/src/EpicManifestParser/Api/ManifestInfo.cs#L138) function in a asynchronous task it returned a **HttpRequestException** with status code 403 (forbidden). Initially I thought it was a problem with my code but after testing using both **FModel** and **Solitude** which worked before I think it is a issue with the parser or with my wifi? The error is not only happening for me but for others too

![image](https://github.com/NotOfficer/EpicManifestParser/assets/79089473/01fa898b-3136-4dbb-a283-c1845195a65c)

**Comment by NotOfficer** [comment]
This should be fixed now, can you confirm?

**Comment by GhostScissors** [comment]
Yes I can confirm it works now. Thank you for your efforts!
