### ISSUE TITLE
Could I use this for downloading a manifest for a past version of a game?

### ISSUE THREAD

**Issue by optixyt0** [NotOfficer/EpicManifestParser#8]
I'm looking to maybe use this in my OGFN launcher, and would like to know if I could use a manifest like this? https://raw.githubusercontent.com/VastBlast/FortniteManifestArchive/main/Fortnite/Windows/21yEPkbqhNy_ePUECE6oTHEmg0SIfw.manifest

**Comment by NotOfficer** [comment]
https://tryitands.ee

**Comment by optixyt0** [comment]
Ok, sorry if I wasted any time
