### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by EmptyEnergy** [NotOfficer/EpicManifestParser#9]
How do you even use this? there is no instructions on the page, how are we supposed to know how to load this?

**Comment by s1btea** [comment]
![20241212_085748.jpg](https://github.com/user-attachments/assets/3efccf98-b0d1-4d4f-b11d-3eb3705f3b00)

Also you can look for examples, like, in fmodel source code or anywhere else. Just use github search.

**Comment by s1btea** [comment]
![20241212_085748.jpg](https://github.com/user-attachments/assets/3efccf98-b0d1-4d4f-b11d-3eb3705f3b00)

Also you can look for examples, like, in fmodel source code or anywhere else. Just use github search.

**Comment by EmptyEnergy** [comment]
> ![20241212_085748.jpg](https://private-user-images.githubusercontent.com/78100130/394978494-3efccf98-b0d1-4d4f-b11d-3eb3705f3b00.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NjkxNzQsIm5iZiI6MTczMzk2ODg3NCwicGF0aCI6Ii83ODEwMDEzMC8zOTQ5Nzg0OTQtM2VmY2NmOTgtYjBkMS00ZDRmLWIxMWQtM2ViMzcwNWYzYjAwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAyMDExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1OGI1YmU2MWMxMDI3ZGRmMGE2YzIwZDBmOWMzZjkxYTU3MjY5OWU1NTZjMjQ4NTczNTU5MmNiNWU4NGE1NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ps7kFEdFtjeTGClSTfHhETYzf1C9WC7E0_cRPZaa24g)
> 
> Also you can look for examples, like, in fmodel source code or anywhere else. Just use github search.

How do you even start/install EpicManifestParser though? i have the manifest i want to parse but i have no idea how to do it

**Comment by s1btea** [comment]
Uh... Learn C#, that's all. You need to code to use this library.

**Comment by EmptyEnergy** [comment]
> Uh... Learn C#, that's all. You need to code to use this library.

well that sucks

**Comment by NotOfficer** [comment]
What do you expect? This is a library, not an app...
